#!/usr/bin/bash
########################################################################
# Begin mountvirtfs
#
# Description : Mount proc, sysfs, and run
#
# Authors     : Cesar Lombao - cesar.lombao@gmail.com
#
# Version     : Lombix 2020 - Bologna
#
########################################################################


      # Make sure /run is available before logging any messages
      # The /run file system is defined in the /usr/etc/fstab
      if ! mountpoint /run >/dev/null; then
         mount /run || failed=1
      fi

      mkdir -p 		/run/lock 	/run/shm
      chmod 1777 	/run/shm 	/run/lock

      #log_info_msg "Mounting virtual file systems: ${INFO}/run" 
      if ! mountpoint /proc >/dev/null; then
         mount -o nosuid,noexec,nodev /proc || failed=1
      fi

      if ! mountpoint /sys >/dev/null; then
         mount -o nosuid,noexec,nodev /sys || failed=1
      fi

      if ! /usr/bin/mountpoint /dev >/dev/null; then
         mount -o mode=0755,nosuid /dev  || failed=1
      fi

      ln -sfn /run/shm /dev/shm
      
      # Make sure /dev/pts exists
      mkdir -p /dev/pts

      # mount /sys/fs/cgroup if not already done
      if ! mountpoint -q /sys/fs/cgroup; then
 	 mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
      fi

      cd /sys/fs/cgroup

      # get/mount list of enabled cgroup controllers
      for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
       	mkdir -p $sys
 	if ! mountpoint -q $sys; then
  		if ! mount -n -t cgroup -o $sys cgroup $sys; then
   			rmdir $sys || true
  		fi
 	fi
       done

      
      exit $failed
      ;;

# End mountvirtfs
