#!/usr/bin/bash
########################################################################
# Begin modules
#
# Description : Module auto-loading script
#
# Authors     : Cesar Lombao
#
# Version     : Lombix 2020 - Bologna
#
########################################################################



	# Is there module support.
	[ -e /proc/modules ] || exit 0


	# Exit if there's no modules file or there are no
      	# valid entries
      	[ -r $MODULES_CFG_FILE ]             || exit 0
      	egrep -qv '^($|#)' $MODULES_CFG_FILE || exit 0

      	# Only try to load modules if the user has actually given us
      	# some modules to load.

      	while read module args; do

        	# Ignore comments and blank lines.
      		case "$module" in
            		""|"#"*) continue ;;
         	esac

         	# Attempt to load the module, passing any arguments provided.
         	modprobe ${module} ${args} >/dev/null

         	# Print the module name if successful, otherwise take note.
         	if [ $? -ne 0 ]; then
            		failedmod="${failedmod} ${module}"
         	fi
     	 done < $MODULES_CFG_FILE

      # Print a failure message with a list of any modules that 
      # may have failed to load.
      if [ -n "${failedmod}" ]; then
         echo ">> ERROR:: Failed to load modules:${failedmod}" 
         exit 1
      fi
      

# End modules
