#!/usr/bin/bash
########################################################################
# Begin console
#
# Description : Sets keymap and screen font
#
# Authors     : Cesar Lombao - cesar.lombao@gmail.com
#
# Version     : Lombix 2020 - Bologna
#
########################################################################


source /etc/rc.d/system-config


	failed=0
	[ -r $CONSOLE_CFG_FILE ] && source $CONSOLE_CFG_FILE


      # Figure out the command to set the console into the
      # desired mode
      if [ "${UNICODE}" -eq "1" ]; then
      
         MODE_COMMAND="echo -en '\033%G' && kbd_mode -u" ||
         MODE_COMMAND="echo -en '\033%@\033(K' && kbd_mode -a"
      fi
	
      # Apply that command to all consoles mentioned in
      # /etc/inittab. Important: in the UTF-8 mode this should
      # happen before setfont, otherwise a kernel bug will
      # show up and the unicode map of the font will not be
      # used.

      for TTY in `grep '^[^#].*respawn:/usr/sbin/agetty' /usr/etc/inittab | grep -o '\btty[[:digit:]]*\b'`
      do
         openvt -f -w -c ${TTY#tty} -- \
            bash -c "${MODE_COMMAND}" || failed=1
      done


      [ -z "${KEYMAP}" ] || loadkeys ${KEYMAP}        


# End console
