#!/usr/bin/bash

export PATH=/usr/bin

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/etc/X11/app-defaults/.Xresources
sysmodmap=/usr/etc/X11/app-defaults/.Xmodmap

# merge in defaults and keymaps

[ -f $sysresources ] 	&& 	xrdb -merge $sysresources
[ -f $sysmodmap ] 		&&  xmodmap 	$sysmodmap
[ -f $userresources ]	&&  xrdb -merge $userresources
[ -f $usermodmap ]		&&	xmodmap 	$usermodmap

# start some nice programs

if [ -d /usr/etc/X11/app-defaults/xinitrc.d ] ; then
 for f in /usr/etc/X11/app-defaults/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Start XFCE
#dbus-launch --exit-with-session startxfce4
#exec startxfce4